//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecrDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int in_id { get; set; }
        public Nullable<System.DateTime> in_sDate { get; set; }
        public Nullable<System.DateTime> in_EDate { get; set; }
        public Nullable<int> rent_period { get; set; }
        public Nullable<int> car_id_FK_ { get; set; }
        public Nullable<int> cus_id_FK_ { get; set; }
        public Nullable<int> user_id_FK_ { get; set; }
    
        public virtual car car { get; set; }
        public virtual customer customer { get; set; }
        public virtual user user { get; set; }
    }
}
